name: Responder al PR
on:
  pull_request:
    types:
      - opened
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - name: Comentar en el PR
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const response = "Este comentario es solo para el autor del PR.";
          const prAuthor = context.payload.pull_request.user.login;
          if (context.actor === prAuthor) {
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: response
            });
          }
